library(tximport)
library(DESeq2)
load("gene_tximport.RData")
colData <- data.frame(Sample=colnames(summarised_to_gene$counts), condition = 1)
dds <- DESeqDataSetFromTximport(summarised_to_gene, colData=colData, design=~1)
dds <- estimateSizeFactors(dds)
sf <- estimateSizeFactorsForMatrix(counts(dds))
sf <- data.frame(sample=names(sf), size_factor= sf)
write.table(sf, file="size_factors.tsv", row.names=FALSE, sep="\t", quote=FALSE)
