
# genome ID
genome: hg38_noalt

# directory where exported data is located
exportdir: export

# location of indexed genome 
genome_dir: /shared/sudlab1/General/mirror/genomes/index

# scratchdir for data not to be backed up
scratchdir: /tmp

# a version string
version: ''

# directory for publishing results on the web
web_dir: ../web

# provide a reference geneset (suffix= ".gtf.gz")
# geneset=refcoding.gtf.gz
# geneset should be in the current directory or a full path provided
geneset: agg-agg-agg.gtf.gz

# THe following fields allow fields other than gene_id and transcript
# id to be used for building the transcript2geneMap. This can be useful
# if you've assembled a gene set and the gene_ids are in something like
# ref_gene_id. If a particular field is not present, the code will
# fall back to gene_id/transcript_id. This is useful for novel genes.

transcript_id_field: transcript_id
gene_id_field: gene_id
#######################################################
database:
    url: sqlite:///./csvdb

    ################################################################
    ## Location of annotation database
    ################################################################
annotations:
    database: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85/csvdb

    # directory with annotation information
    dir: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85

    ################################################################
    ## program options
    ################################################################
    #
    # salmon options
    #
    ################################################################
salmon:

    use_genome_decoy: True
    
    # see `salmon quant --help` for explanation of library types
    # ISF == fr-secondstrand in tophat
    libtype: A

    # String providing additional options to append to the salmon quant
    # command
    # optional arguments include:
    # --extraSensitive
    # may use --gcBias, but be aware this will double the run time and 
    # requires a lot of memory, which will in turn prolong the waiting
    # time for having our tasks run through the cluster
    # using --gcBias when running hundreds of samples is not ideal
    options: --writeUnmappedNames --validateMappings --gcBias

    # kmer size for salmon library
    kmer: 31

    # number of bootstrap samples
    # Note: you need to bootstrap for differential expression with sleuth
    # if there are no technical replicates
    bootstraps: 100
    # bootstrap or Gibbs
    bootstrap_type: bootstrap

    # string to append to the salmon index command to provide specific
    # options
    # from salmon >= v0.5.0, an index type is required
    # specify one of --type=fmd or --type=quasi
    index_options:
    index_threads: 4
    index_memory: 8G
    
    threads: 4

    memory: 4G

    #####################################################
report:
    # number of threads to use to build the documentation
    threads: 1

    # directory for html documentation
    html: report/html

    # directory for doctrees
    doctrees: report/doctrees

    # prefix for publishing
    prefix: default

    # report engine to use
    engine: cgatreport
